<?php

return
 [
     'access' =>[
         'category-list' => 'category_list',
         'category-add' => 'category_add',
         'category-edit' => 'category_edit',
         'category-delete' => 'category_delete',
         'order-confirm' => 'order_confirm',
         'order-list' => 'order_list',
         'order-details' => 'order_details',
         'order-delete' => 'order_delete',
         'brand-list' => 'brand_list',
         'brand-add' => 'brand_add',
         'brand-edit' => 'brand_edit',
         'brand-delete' => 'brand_delete',
         'products-list' => 'products_list',
         'products-add' => 'products_add',
         'products-edit' => 'products_edit',
         'products-delete' => 'products_delete',
         'productAtrribute-list' => 'productAtrribute_list',
         'productAtrribute-add' => 'productAtrribute_add',
         'productAtrribute-edit' => 'productAtrribute_edit',
         'productAtrribute-delete' => 'productAtrribute_delete',
         'slider-list' => 'slider_list',
         'slider-add' => 'slider_add',
         'slider-edit' => 'slider_edit',
         'slider-delete' => 'slider_delete',
         'footer-list' => 'footer_list',
         'footer-edit' => 'footer_edit',
         'homeCategory-list' => 'homeCategory_list',
         'homeCategory-edit' => 'homeCategory_edit',
         'payment-list' => 'payment_list',
         'payment-add' => 'payment_add',
         'payment-edit' => 'payment_edit',
         'payment-delete' => 'payment_delete',
         'posts-list' => 'posts_list',
         'posts-add' => 'posts_add',
         'posts-edit' => 'posts_edit',
         'posts-delete' => 'posts_delete',
         'feedback-list' => 'feedback_list',
         'coupon-list' => 'coupon_list',
         'coupon-add' => 'coupon_add',
         'coupon-edit' => 'coupon_edit',
         'coupon-delete' => 'coupon_delete',
         'sale-list' => 'sale_list',
         'sale-edit' => 'sale_edit',

     ],
     'table_module' => [
         'category',
         'order',
         'brand',
         'products',
         'productAtrribute',
         'slider',
         'footer',
         'homeCategory',
         'posts',
         'feedback',
         'payment',
         'coupon',
         'sale',
     ],
     'module_childrent' => [
         'list',
         'add',
         'edit',
         'delete',
     ],
    ];
